import { type } from 'arktype';

export const GithubPushSchema = type({
  ref: 'string',
  before: 'string',
  after: 'string',
  repository: {
    id: 'number',
    name: 'string',
    full_name: 'string',
    private: 'boolean',
    owner: {
      name: 'string',
      email: 'string?',
      login: 'string',
      id: 'number',
      avatar_url: 'string',
      url: 'string',
    },
    html_url: 'string',
    description: 'string|null',
    fork: 'boolean',
    url: 'string',
    created_at: 'number|string',
    updated_at: 'string',
    pushed_at: 'number|string',
    homepage: 'string|null',
    size: 'number',
    stargazers_count: 'number',
    watchers_count: 'number',
    language: 'string|null',
    has_issues: 'boolean',
    has_projects: 'boolean',
    has_downloads: 'boolean',
    has_wiki: 'boolean',
    has_pages: 'boolean',
    forks_count: 'number',
    mirror_url: 'string|null',
    open_issues_count: 'number',
    forks: 'number',
    open_issues: 'number',
    watchers: 'number',
    default_branch: 'string',
  },
  pusher: {
    name: 'string',
    email: 'string?',
  },
  sender: {
    login: 'string',
    id: 'number',
    avatar_url: 'string',
    url: 'string',
  },
  commits: type([
    {
      id: 'string',
      tree_id: 'string',
      distinct: 'boolean',
      message: 'string',
      timestamp: 'string',
      url: 'string',
      author: {
        name: 'string',
        email: 'string',
        username: 'string?',
      },
      committer: {
        name: 'string',
        email: 'string',
        username: 'string?',
      },
      added: 'string[]',
      removed: 'string[]',
      modified: 'string[]',
    },
    '[]',
  ]),
  'head_commit?': {
    id: 'string',
    tree_id: 'string',
    distinct: 'boolean',
    message: 'string',
    timestamp: 'string',
    url: 'string',
    author: {
      name: 'string',
      email: 'string',
      username: 'string?',
    },
    committer: {
      name: 'string',
      email: 'string',
      username: 'string?',
    },
    added: 'string[]',
    removed: 'string[]',
    modified: 'string[]',
  },
});
